---
title: "UBCF and IBCF"
output: html_document
date: "2022-12-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## UBCF


```{r}
#Initial Code
library(recommenderlab)
myurl = "https://liangfgithub.github.io/MovieData/"
ratings = read.csv(paste0(myurl, 'ratings.dat?raw=true'), 
                   sep = ':',
                   colClasses = c('integer', 'NULL'), 
                   header = FALSE)
colnames(ratings) = c('UserID', 'MovieID', 'Rating', 'Timestamp')
i = paste0('u', ratings$UserID)
j = paste0('m', ratings$MovieID)
x = ratings$Rating
tmp = data.frame(i, j, x, stringsAsFactors = T)
Rmat = sparseMatrix(as.integer(tmp$i), as.integer(tmp$j), x = tmp$x)
rownames(Rmat) = levels(tmp$i)
colnames(Rmat) = levels(tmp$j)
Rmat = new('realRatingMatrix', data = Rmat)

train = Rmat[1:500, ]
test = Rmat[501, ]

#normalize
newdata = as(test, "matrix") 
data = as(train, "matrix") 

user.means = rowMeans(data, na.rm = TRUE) 
data = data - user.means 

newuser.means = rowMeans(newdata, na.rm = TRUE) 
newdata = newdata - newuser.means 

#Cosine Similarity
sim = rep(0, dim(data)[1]) 
for(i in 1:length(sim)) { 
  tmp.y = as.vector(newdata)
  ind.y = which(!is.na(tmp.y))
  tmp.x = data[i, ] 
  ind.x = which(!is.na(tmp.x)) 
  ind  = intersect(ind.x, ind.y)
  if (length(ind) > 0){ 
    tmp.x = tmp.x[ind]
    tmp.y = tmp.y[ind] 
    sim[i] = sum(tmp.x * tmp.y) / sqrt(sum(tmp.x^2) * sum(tmp.y^2)) 
    } 
  } 
sim = (1 + sim)/2

##################
sort = tail(sort(sim), 20)
val = sort[1]
sim[sim < val] = 0


mypred = colSums(data * sim, na.rm = TRUE) / colSums((!is.na(data)) * sim)
mypred = mypred + newuser.means


mypred[!is.na(newdata)] = NA
mypred[is.infinite(mypred)] = NA
mypred[is.nan(mypred)]=NA

# UBCF
recommender.UBCF <- Recommender(train, method = "UBCF",
                                parameter = list(normalize = 'center', 
                                                 method = 'Cosine', 
                                                 nn = 20))

p.UBCF <- predict(recommender.UBCF, test, type="ratings")
p.UBCF <- as.numeric(as(p.UBCF, "matrix"))

sum(is.na(p.UBCF) != is.na(mypred)) ### should be zero
max(abs(p.UBCF - mypred), na.rm = TRUE)  ### should be less than 1e-06 

```

## IBCF

```{r}
#Initial Code
library(recommenderlab)
myurl = "https://liangfgithub.github.io/MovieData/"
ratings = read.csv(paste0(myurl, 'ratings.dat?raw=true'), 
                   sep = ':',
                   colClasses = c('integer', 'NULL'), 
                   header = FALSE)
colnames(ratings) = c('UserID', 'MovieID', 'Rating', 'Timestamp')
i = paste0('u', ratings$UserID)
j = paste0('m', ratings$MovieID)
x = ratings$Rating
tmp = data.frame(i, j, x, stringsAsFactors = T)
Rmat = sparseMatrix(as.integer(tmp$i), as.integer(tmp$j), x = tmp$x)
rownames(Rmat) = levels(tmp$i)
colnames(Rmat) = levels(tmp$j)
Rmat = new('realRatingMatrix', data = Rmat)

train = Rmat[1:500, ]
test = Rmat[501, ]


#normalize
newdata = as(test, "matrix") 
data = as(train, "matrix") 
user.means = rowMeans(data, na.rm = TRUE) 
data = data - user.means 

#Cosine Similarity
sim = proxy::simil(data, method = "cosine", by_rows = FALSE) 
sim = (1 + sim)/2 
sim_mat = as.matrix(sim)

for(i in 1:ncol(data)){
  ord1 = order(sim_mat[i, ], decreasing = FALSE, na.last = FALSE)
  ord = tail(ord1, 30)
  sim_mat[i, -ord] = NA
}

##################
nonNA = which(!is.na(newdata))
ent = as.vector(newdata[nonNA])
sim = t(sim_mat[, nonNA])
mypred = colSums(sim * ent, na.rm = T)/rowSums(sim_mat[, nonNA], na.rm = T)
mypred = as(mypred, "matrix")
mypred[!is.na(newdata)] = NA
mypred[is.infinite(mypred)] = NA
mypred[is.nan(mypred)]=NA


# IBCF
recommender.IBCF <- Recommender(train, method = "IBCF",
                                parameter = list(normalize = 'center', 
                                                 method = 'Cosine', 
                                                 k = 30))

p.IBCF <- predict(recommender.IBCF, test, type="ratings")
p.IBCF <- as.numeric(as(p.IBCF, "matrix"))

## first output: should be less than 10
sum(is.na(p.IBCF) != is.na(mypred))  

## second output: should be less than 10%
mydiff = abs(p.IBCF - mypred)
sum(mydiff[!is.na(mydiff)] > 1e-6) / sum(!is.na(mydiff)) 
```
